# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# server-gitssh pipeline

name: $(Build.BuildId)

parameters:
- name: releaseBuildOverride
  displayName: Release Build (default = not released)
  type: string
  default: none
  values:
    - none
    - release
- name: publishOverride
  displayName: Publish Override (default = based on branch)
  type: string
  default: default
  values:
    - default
    - skip
    - force
- name: buildToolsVersionToInstall
  displayName: Fluid build tools version (default = installs version in repo)
  type: string
  default: repo

trigger:
  branches:
    include:
    - main
    - next
    - lts
  paths:
    include:
    - .prettierignore
    - fluidBuild.config.cjs
    - server/gitssh
    - tools/pipelines/server-gitssh.yml
    - tools/pipelines/templates/1ES/build-docker-service.yml
    - tools/pipelines/templates/1ES/include-vars.yml
    - tools/pipelines/templates/1ES/include-install-pnpm.yml
    - tools/pipelines/templates/1ES/include-publish-docker-service.yml
    - tools/pipelines/templates/1ES/include-publish-docker-service-steps.yml
    - tools/pipelines/templates/1ES/include-git-tag-steps.yml
    - tools/pipelines/templates/1ES/include-use-node-version.yml

pr:
  branches:
    include:
    - main
    - next
    - lts
    - release/*
  paths:
    include:
    - .prettierignore
    - fluidBuild.config.cjs
    - server/gitssh
    - tools/pipelines/server-gitssh.yml
    - tools/pipelines/templates/1ES/build-docker-service.yml
    - tools/pipelines/templates/1ES/include-vars.yml
    - tools/pipelines/templates/1ES/include-install-pnpm.yml
    - tools/pipelines/templates/1ES/include-use-node-version.yml

variables:
- template: /tools/pipelines/templates/1ES/include-vars.yml@self
  parameters:
    releaseImage: true
    publishOverride: ${{ parameters.publishOverride }}
    releaseBuildOverride: ${{ parameters.releaseBuildOverride }}
    buildNumberInPatch: true

extends:
  template: /tools/pipelines/templates/1ES/build-docker-service.yml@self
  parameters:
    testBuild: ${{ variables.testBuild }}
    pushImage: ${{ variables.pushImage }}
    buildToolsVersionToInstall: ${{ parameters.buildToolsVersionToInstall }}
    buildDirectory: server/gitssh
    containerName: fluidframework/routerlicious/gitssh
    setVersion: false
    tagName: gitssh
