# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# server-historian pipeline

name: $(Build.BuildId)

parameters:
- name: releaseBuildOverride
  displayName: Release Build (default = not released)
  type: string
  default: none
  values:
  - none
  - release
- name: releaseKind
  displayName: Release Kind
  type: string
  default: both
  values:
  - both
  - npm
  - docker
- name: publishOverride
  displayName: Publish Override (default = based on branch)
  type: string
  default: default
  values:
  - default
  - skip
  - force
- name: buildToolsVersionToInstall
  displayName: Fluid build tools version (default = installs version in repo)
  type: string
  default: repo

trigger:
  branches:
    include:
    - main
    - next
    - lts
  paths:
    include:
    - .prettierignore
    - fluidBuild.config.cjs
    - server/historian
    - tools/pipelines/server-historian.yml
    - tools/pipelines/templates/1ES/build-docker-service.yml
    - tools/pipelines/templates/1ES/include-set-package-version.yml
    - tools/pipelines/templates/1ES/include-vars.yml
    - tools/pipelines/templates/1ES/include-install-pnpm.yml
    - tools/pipelines/templates/1ES/include-generate-notice-steps.yml
    - tools/pipelines/templates/1ES/include-publish-npm-package.yml
    - tools/pipelines/templates/1ES/include-publish-npm-package-deployment.yml
    - tools/pipelines/templates/1ES/include-publish-npm-package-steps.yml
    - tools/pipelines/templates/1ES/include-publish-docker-service.yml
    - tools/pipelines/templates/1ES/include-publish-docker-service-steps.yml
    - tools/pipelines/templates/1ES/include-git-tag-steps.yml
    - tools/pipelines/templates/1ES/include-use-node-version.yml

pr:
  branches:
    include:
    - main
    - next
    - lts
    - release/*
  paths:
    include:
    - .prettierignore
    - fluidBuild.config.cjs
    - server/historian
    - tools/pipelines/server-historian.yml
    - tools/pipelines/templates/1ES/build-docker-service.yml
    - tools/pipelines/templates/1ES/include-set-package-version.yml
    - tools/pipelines/templates/1ES/include-vars.yml
    - tools/pipelines/templates/1ES/include-install-pnpm.yml
    - tools/pipelines/templates/1ES/include-use-node-version.yml

variables:
- template: /tools/pipelines/templates/1ES/include-vars.yml@self
  parameters:
    releaseImage: true
    publishOverride: ${{ parameters.publishOverride }}
    releaseBuildOverride: ${{ parameters.releaseBuildOverride }}
    buildNumberInPatch: true

extends:
  template: /tools/pipelines/templates/1ES/build-docker-service.yml@self
  parameters:
    testBuild: ${{ variables.testBuild }}
    pushImage: ${{ variables.pushImage }}
    releaseKind: ${{ parameters.releaseKind }}
    buildToolsVersionToInstall: ${{ parameters.buildToolsVersionToInstall }}
    buildDirectory: server/historian
    containerName: fluidframework/routerlicious/historian
    # We need to install only the root dependencies; historian has native deps that don't install in CI since we use
    # Docker to do the actual build in CI. We need the root dependencies so setting package versions works.
    packageManagerInstallCommand: 'pnpm install --workspace-root --frozen-lockfile'
    packageManager: pnpm
    test: test
    tagName: historian
    lint: true
    pack: true
    checks:
    - prettier
