# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# include-publish-docker-service-steps

parameters:
- name: environment
  type: string

- name: pool
  type: object
  default: Small-1ES

- name: containerRegistry
  type: string

- name: containerTag
  type: string

- name: containerRegistryUrl
  type: string

- name: containerName
  type: string

- name: tagName
  type: string
  default:

jobs:
- deployment: publish_${{ replace(parameters.environment, '-', '_') }}
  displayName: Publish ${{ parameters.environment }}
  environment: ${{ parameters.environment }}
  pool: ${{ parameters.pool }}
  workspace:
    clean: all
  variables:
    version: $[ stageDependencies.build.build.outputs['SetVersion.version']]
    containerTagSuffix: $(version)
  strategy:
    runOnce:
        deploy:
            steps:
            - download: none
            - task: Docker@2
              displayName: Login to ACR
              inputs:
                command: login
                containerRegistry: ${{ parameters.containerRegistry }}

            - task: Docker@1
              displayName: Pull image
              inputs:
                action: 'Run a Docker command'
                customCommand: 'pull ${{ parameters.containerTag }}'

            #Remove this line - added to test if the below line is making ES1 complain
            # Also convert all the Docker@1 back to Docker@0
            - task: Docker@1
              displayName: Tag image
              inputs:
                action: 'Run a Docker command'
                customCommand: 'tag ${{ parameters.containerTag }} ${{ parameters.containerRegistryUrl }}/${{ parameters.containerName }}:$(containerTagSuffix)'

            - task: Docker@1
              displayName: Tag image
              inputs:
                action: 'Run a Docker command'
                customCommand: 'tag ${{ parameters.containerTag }} ${{ parameters.containerRegistryUrl }}/${{ parameters.containerName }}:latest'

            - task: Docker@2
              displayName: Docker Push
              inputs:
                containerRegistry: ${{ parameters.containerRegistry }}
                repository: ${{ parameters.containerName }}
                command: push
                tags: |
                  $(containerTagSuffix)
                  latest

            - template: include-git-tag-steps.yml
              parameters:
                tagName: ${{ parameters.tagName }}
