name: "pr-check-changeset"

on:
  pull_request_target:
    types: [labeled, unlabeled, opened, synchronize, reopened]

jobs:
  # When a PR has the changeset-required label, check if it has a changeset.
  # This job must be triggered by pull_request, NOT pull_request_target so that it executes in a safe context.
  changeset-required:
    name: Changeset required
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'changeset-required')
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
        with:
          fetch-depth: "0" # all history
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }} # Check out the head commit, not the merge commit

      # install and configure node, pnpm and the changeset tools
      - uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # ratchet:pnpm/action-setup@v2
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # ratchet:actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: Install tools
        run: |
          # We only need to install the root dependencies
          pnpm install -w --frozen-lockfile

      # Add the remote for debugging
      - run: git remote add upstream https://github.com/microsoft/FluidFramework
      - run: git fetch upstream
      - run: git log -1

      # Check whether a changeset was added. This step will have the outcome 'failure' if there is no changeset.
      - id: changeset-status
        name: Changeset status
        run: |
          set +e # don't exit on failure
          flub check changeset --branch=${{ github.base_ref }}
          echo "$?" > ./changeset-status

      - name: Upload changeset status
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # ratchet:actions/upload-artifact@v3
        with:
          name: changeset-status
          path: ./changeset-status
          retention-days: 3

  # Any PR without the changeset-required label will be ignored.
  changeset-not-required:
    name: Changeset not required
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'changeset-required') }}
    steps:
      - id: changeset-status
        name: Changeset disabled
        run: |
          # Always output 0 to signal that changesets aren't needed
          echo "0" > ./changeset-status

      - name: Upload changeset status
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # ratchet:actions/upload-artifact@v3
        with:
          name: changeset-status
          path: ./changeset-status
          retention-days: 3
